

name: Build and deploy ASP.Net Core app to Azure Web App - clickimoveis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore ./src/click-imoveis.sln

      - name: Build do projeto
        run: dotnet build ./src/click-imoveis.csproj --configuration Release --no-restore

      - name: Publicar projeto
        run: dotnet publish ./src/click-imoveis.csproj -c Release -o ./publish --no-build

      - name: Zipar a pasta publish
        run: Compress-Archive -Path ./publish/* -DestinationPath ./app.zip
        shell: pwsh

      - name: Upload do artefato zipado
        uses: actions/upload-artifact@v4
        with:
          name: app-publicada-zip
          path: ./app.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Baixar artefato zipado
        uses: actions/download-artifact@v4
        with:
          name: app-publicada-zip

      - name: Login no Azure
        uses: azure/login@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Deploy no Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: clickimoveis
          slot-name: Production
          package: ./app.zip


